### ISSUE TITLE
Specifying `ssl => true` leads to exception "URI::InvalidURIError: bad URI(is not URI?)"

### ISSUE THREAD

**Issue by webmat** [logstash-plugins/logstash-filter-elasticsearch#102]
When specifying `ssl => true` (with or without `ca_cert` param), the URL string is not interpolated correctly. Here's the error raised:

```
[2018-06-20T14:18:43,541][WARN ][logstash.filters.elasticsearch] Failed to query elasticsearch for previous event {:index=>"cert", :query=>"@timestamp:*", :event=>#<LogStash::Event:0x7ad689eb>, :error=>#<URI::InvalidURIError: bad URI(is not URI?): https://{:host=>"https://example.us-central1.gcp.cloud.es.io:9243/", :scheme=>"https"}:https>}
```

Notice the URL string appears to contain the full params hash (`hash.to_s`): `https://{:host=>"https://example.us-central1.gcp.cloud.es.io:9243/", :scheme=>"https"}` instead of templating the fields in a string template (e.g. `"%{scheme}://%{host}" % { scheme: 'https', host: '...' }`)

This particular trace was generated by the following configuration (subdomain of the cloud instance changed):

```
bin/logstash --log.level debug -e "input { generator { count =>  3 } }
filter { elasticsearch {
  user => elastic password => '$ES_PWD' hosts => ['https://example.us-central1.gcp.cloud.es.io:9243/']
  index => 'cert' query => '@timestamp:*' sort => '_id' fields => { 'sequence' => 'last_sequence' }
  ssl => true
} }
output { stdout {} elasticsearch {
  user => elastic password => '$ES_PWD' hosts => ['https://example.us-central1.gcp.cloud.es.io:9243/']
  index => 'cert'
} }"
```

## Known workaround

Specify all hosts with their `https://` prefix and do not specify the `ssl` attribute.

## Full stack trace

`#<URI::InvalidURIError: bad URI(is not URI?): https://{:host=>"https://example.us-central1.gcp.cloud.es.io:9243/", :scheme=>"https"}:https>`

```
 "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:67:in `split'",
 "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:73:in `parse'",
 "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/common.rb:227:in `parse'",
 "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/common.rb:714:in `URI'",
 "org/jruby/RubyMethod.java:127:in `call'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/utils.rb:258:in `URI'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:309:in `url_prefix='",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:77:in `initialize'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `__build_connection'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:138:in `block in __build_connections'",
 "org/jruby/RubyArray.java:2486:in `map'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:130:in `__build_connections'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:40:in `initialize'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:114:in `initialize'",
 "/Users/mat/work/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport.rb:26:in `new'",
 "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch/client.rb:28:in `initialize'",
 "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:145:in `new_client'",
 "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:149:in `block in get_client'",
 "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:149:in `get_client'",
 "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:93:in `filter'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'",
 "org/jruby/RubyArray.java:1734:in `each'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/filter_delegator.rb:44:in `multi_filter'",
 "(eval):46:in `block in filter_func'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:443:in `filter_batch'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:422:in `worker_loop'",
 "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:384:in `block in start_workers'"
```

**Comment by webmat** [comment]
The problem appears to be with [this line](https://github.com/logstash-plugins/logstash-filter-elasticsearch/blob/79d96840475baeb90445483c0543c3905232c140/lib/logstash/filters/elasticsearch/client.rb#L23). It replaces URL strings with ruby hashes.

**Comment by webmat** [comment]
Currently setting `ssl => true` is completely broken in this plugin. I'm currently adding tests to describe the desired behaviour. However the full rewrite of the HTTP subsystem we want to do, to bring all 3 ES plugins in line is out of scope for this bug fix.

Here's how I intend to make it behave, after this bug fix.

```ruby
    it "should accept schema-less hosts"
    it "should accept hosts with a schema"
    it "should add https to schema-less hosts when specifying ssl true"
    it "should log an error and raise, when specifying a schema in at least one host, and setting ssl true"
    it "should log an error and raise, when specifying a schema in at least one host, and setting ssl false"

```
Note that the last two are a bit more strict than the behaviour of output-elasticsearch. Specifying any schema in the host list, then setting `ssl` (which is meant to add a schema everywhere for them) is simply a user passing conflicting args.

I don't think we should jump through hoops to try to accomodate this behaviour. The user should either specify schema for all hosts, or not specify them for any. Then if you set `ssl => true` we add `https://` for you (adding `ssl => false` doesn't need to do anything, ES::Client will default to http).

If someone needs to specify a mixed set of SSL and not SSL, it's just as simple: specify your http and https schemas in the host list and don't touch the `ssl` attribute.

Of course the error will make it clear that they should use one or the other, not both. Same for the documentation for `ssl`.

WDYT, @jsvd @robbavey?

**Comment by webmat** [comment]
Here's the behaviour when someone triggers this conflicting config situation:

```
[2018-06-28T14:07:00,960][ERROR][logstash.filters.elasticsearch] Conflicting configuration detected: you cannot specify a schema in your hosts and set the 'ssl' option at the same time. You must use one or the other. {:ssl=>true, :hosts=>["https://example.us-central1.gcp.cloud.es.io:9243/"]}
[2018-06-28T14:07:00,985][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x1520c155 @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @id=\"a0f2c1c31327708709cba79086afa8959198494108fe2c4db284de40ddc05c81\", @klass=LogStash::Filters::Elasticsearch, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x72b8264f @metric=#<LogStash::Instrument::Metric:0x60598838 @collector=#<LogStash::Instrument::Collector:0x34a71b53 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x279e4efb @store=#<Concurrent::Map:0x00000000000fb0 entries=2 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x3462253f>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=62 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :a0f2c1c31327708709cba79086afa8959198494108fe2c4db284de40ddc05c81, :events]>, @filter=<LogStash::Filters::Elasticsearch user=>\"elastic\", password=><password>, hosts=>[\"https://ecb5659675444fdea0ec2129b65410c0.us-central1.gcp.cloud.es.io:9243/\"], index=>\"cert\", query=>\"@timestamp:*\", sort=>\"_id\", fields=>{\"sequence\"=>\"last_sequence\"}, ssl=>true, id=>\"a0f2c1c31327708709cba79086afa8959198494108fe2c4db284de40ddc05c81\", enable_metric=>true, periodic_flush=>false, enable_sort=>true, result_size=>1, tag_on_failure=>[\"_elasticsearch_lookup_failure\"]>>", :error=>"Aborting due to conflicting configuration", :thread=>"#<Thread:0x4921c1ba run>"}
[2018-06-28T14:07:01,002][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Aborting due to conflicting configuration>, :backtrace=>["/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch/client.rb:24:in `initialize'", "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:143:in `new_client'", "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:147:in `block in get_client'", "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:147:in `get_client'", "/Users/mat/work/elastic/plugins/logstash-filter-elasticsearch/lib/logstash/filters/elasticsearch.rb:74:in `register'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:340:in `register_plugin'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:351:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:351:in `register_plugins'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:729:in `maybe_setup_out_plugins'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:361:in `start_workers'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `run'", "/Users/mat/work/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:248:in `block in start'"], :thread=>"#<Thread:0x4921c1ba run>"}
[2018-06-28T14:07:01,034][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
...
[2018-06-28T14:07:06,309][DEBUG][logstash.agent           ] Shutting down all pipelines {:pipelines_count=>1}
```

Actually should I be using `fatal`, since I'm basically crashing Logstash here?

**Comment by andrewbanchich** [comment]
I can confirm I've been getting this as well.

**Comment by nilskuhn** [comment]
This bug cost me some hours :(

One suggestion and one please I have:

**Suggestion**
Could you please remove `ssl` option from [official documentation](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elasticsearch.html#plugins-filters-elasticsearch-ssl) or better document the problem with it there.

**Question**
_However the full rewrite of the HTTP subsystem we want to do, to bring all 3 ES plugins in line is out of scope for this bug fix._
Can I see new plugin versions already somewhere as an alpha or beta? 

Best regards, Nils

**Comment by breml** [comment]
Issue #129 is related to this as well.

**Comment by edmocosta** [comment]
Thank you very much for taking the time to open this issue.

I'm closing it as It seems to be already fixed by this PR https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/156. Please feel free to reopen if the problem still exists. Thanks!
