### ISSUE TITLE
Default setting for "hosts" not working

### ISSUE THREAD

**Issue by demsjf8** [logstash-plugins/logstash-filter-elasticsearch#125]
Running logstash and elasticsearch on the same host, I wanted to use the default configuration for "hosts" of the elasticsearch filter plugin by simply omitting to explicit set a value for "hosts", i.e. it should implicitly use ["localhost:9200"].

However, logstash cannot successfully connect and instead throws an error message, it seems the actual default value in the code is ["//localhost:9200"] so that the URL built does not contain a valid host name, i.e. the URL ends up to be http:////localhost:9200 (with four backslashes).

`[2020-02-25T16:49:38,156][INFO ][logstash.filters.elasticsearch][main] New ElasticSearch filter client {:hosts=>["//localhost:9200"]}

[2020-02-25T16:49:38,221][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Manticore::ClientProtocolException: URI does not specify a valid host name: http:////localhost:9200/>, :backtrace=>["/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:274:in `call_once'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:158:in `code'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `block in perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/ping.rb:20:in `ping'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.7.0/lib/logstash/filters/elasticsearch.rb:270:in `test_connection!'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.7.0/lib/logstash/filters/elasticsearch.rb:92:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:502:in `maybe_setup_out_plugins'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:212:in `start_workers'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/root/logstash-7.6.0/bin/my-config.conf"], :thread=>"#<Thread:0xb784414 run>"}`

Logstash 7.6.0 on CentOS 8, logstash-filter-elasticsearch version 3.7.0

Filter plugin config section:

`        elasticsearch {
                query => "_id:%{[my_document_id]}"
                fields => { "[last_trust_decision][result]" => "old_result" }
                index => "my-index"
        }
`

**Comment by kares** [comment]
Thanks for the report, seems this has been broken for a while now -> 7.13 behaving the same (7.14.0 as well):
`$ bin/logstash -e "filter { elasticsearch { user => 'elastic' password => 'elastic' } }"`
```
[2021-08-10T11:28:08,278][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.13.0", "jruby.version"=>"jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 25.302-b08 on 1.8.0_302-b08 +indy +jit [linux-x86_64]"}
[2021-08-10T11:28:08,968][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-08-10T11:28:09,040][WARN ][logstash.agent           ] Setting `pipeline.ecs_compatibility` given as `v1`; values other than `disabled` are currently considered BETA and may have unintended consequences when upgrading minor versions of Logstash.
[2021-08-10T11:28:10,449][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-08-10T11:28:11,471][INFO ][org.reflections.Reflections] Reflections took 70 ms to scan 1 urls, producing 24 keys and 48 values 
[2021-08-10T11:28:15,982][INFO ][logstash.filters.elasticsearch][main] New ElasticSearch filter client {:hosts=>["//localhost:9200"]}
[2021-08-10T11:28:16,742][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Manticore::ClientProtocolException: URI does not specify a valid host name: http:////localhost:9200/>, :backtrace=>["/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.0-java/lib/manticore/response.rb:37:in `block in initialize'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.0-java/lib/manticore/response.rb:79:in `call'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.0-java/lib/manticore/response.rb:274:in `call_once'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.0-java/lib/manticore/response.rb:158:in `code'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `block in perform_request'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/ping.rb:20:in `ping'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:310:in `test_connection!'", "/home/kares/workspace/work/elastic/logstash-7.13.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:117:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/home/kares/workspace/work/elastic/logstash-7.13.0/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["config string"], :thread=>"#<Thread:0xb2c59f4 run>"}

```
