### ISSUE TITLE
Fix 8.0 testing due to dropping of document types

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-elasticsearch#127]
Currently two integration tests against ES 8.0.0 SNAPSHOT fail:

```
1) LogStash::Filters::Elasticsearch should enhance the current event with new data
   Failure/Error: es.index(params)

   Elasticsearch::Transport::Transport::Errors::BadRequest:
     [400] {"error":"no handler found for uri [/logs/doc] and method [POST]"}
   # ./spec/es_helper.rb:27:in `index_doc'
   # ./spec/filters/integration/elasticsearch_spec.rb:30:in `block in <main>'
   # ./spec/filters/integration/elasticsearch_spec.rb:29:in `block in <main>'

2) LogStash::Filters::Elasticsearch when retrieving a list of elements should enhance the current event with new data
   Failure/Error: es.index(params)

   Elasticsearch::Transport::Transport::Errors::BadRequest:
     [400] {"error":"no handler found for uri [/logs/doc] and method [POST]"}
   # ./spec/es_helper.rb:27:in `index_doc'
   # ./spec/filters/integration/elasticsearch_spec.rb:30:in `block in /usr/share/plugins/plugin/spec/filters/integration/elasticsearch_spec.rb'
   # ./spec/filters/integration/elasticsearch_spec.rb:29:in `block in /usr/share/plugins/plugin/spec/filters/integration/elasticsearch_spec.rb'
```

**Comment by mashhurs** [comment]
I think this is old issue and tests are passing.
