### ISSUE TITLE
does not work properly with updated ES client

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-filter-elasticsearch#147]
**Logstash information**:

Please include the following information:

Logstash version (e.g. `bin/logstash --version`) **7.14.0**

**Description of the problem including expected versus actual behavior**:

The problem relates to a elasticsearch client dependency update, for LS < 7.14.0 the version used was 5.0.5, 
in 7.14.0 LS forced a requirement of `>7` and ended up with version 7.5.0 which does not work properly.

**Steps to reproduce**:

`bin/logstash -e "filter { elasticsearch { user => 'elastic' password => 'elastic' hosts => 'http://localhost:9200' } }"`

NOTE: `hosts` needed due broken default on the field: https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/125

**Provide logs (if relevant)**:

**7.13.0** works while **7.14.0** fails with 401 (failing to pass basic auth header):
```
[2021-08-10T11:34:59,488][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.14.0", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 25.302-b08 on 1.8.0_302-b08 +indy +jit [linux-x86_64]"}
[2021-08-10T11:34:59,537][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/queue"}
[2021-08-10T11:34:59,557][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/dead_letter_queue"}
[2021-08-10T11:35:00,147][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-08-10T11:35:00,201][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"f07279a0-4967-4ef8-b508-ba191b55fefb", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/uuid"}
[2021-08-10T11:35:03,573][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9601}
[2021-08-10T11:35:04,668][INFO ][org.reflections.Reflections] Reflections took 167 ms to scan 1 urls, producing 120 keys and 417 values 
[2021-08-10T11:35:09,507][INFO ][logstash.filters.elasticsearch][main] New ElasticSearch filter client {:hosts=>["http://localhost:9200"]}
[2021-08-10T11:35:10,466][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] >, :backtrace=>["/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/ping.rb:23:in `ping'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:310:in `test_connection!'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:117:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1820:in `each'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["config string"], :thread=>"#<Thread:0x6c7c724f run>"}
[2021-08-10T11:35:10,470][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
```

**Comment by kares** [comment]
upstream bug report (*elasticsearch* gem versions 7.2.0 - 7.14.0 all have this issue): https://github.com/elastic/elasticsearch-ruby/issues/1428
